# Generated by Django 5.2.12 on 2026-04-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_count', models.IntegerField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=250)),
                ('section_1', models.TextField()),
                ('section_2', models.TextField()),
                ('section_3', models.TextField()),
                ('section_4', models.TextField()),
                ('answers', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('duration', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
