# Generated by Django 5.2.12 on 2026-04-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsTable',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ListeningSubmission',
        ),
        migrations.CreateModel(
            name='ReadingResults',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.resultstable')),
                ('test_id', models.CharField(max_length=50)),
                ('reading_row_answers', models.JSONField()),
                ('reading_correct_count', models.IntegerField()),
                ('reading_mark', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='WritingResults',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.resultstable')),
                ('test_id', models.CharField(max_length=50)),
                ('task1_text', models.TextField()),
                ('task2_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListeningResults',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.resultstable')),
                ('listening_row_answers', models.JSONField()),
                ('listening_correct_count', models.IntegerField()),
                ('listening_mark', models.DecimalField(decimal_places=1, max_digits=2)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listeningtest')),
            ],
        ),
    ]
