# Generated by Django 5.2.12 on 2026-04-10 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='listening_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listening test',
                'verbose_name_plural': 'Listening testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('audio_file', models.FileField(upload_to='listening/audios/')),
                ('audio_duration_sec', models.PositiveIntegerField(default=0)),
                ('extra_minutes', models.PositiveSmallIntegerField(default=2)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.listeningtest')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sectionlar',
                'ordering': ['test', 'order_num'],
                'unique_together': {('test', 'order_num')},
            },
        ),
    ]
