# Generated by Django 5.2.12 on 2026-04-22 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listeningsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='answers',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
