# Generated by Django 5.2.12 on 2026-04-25 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_readingresults_test_id_readingtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='passage_1_test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_2_test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_3_test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
