# Generated by Django 5.2.12 on 2026-04-23 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listeningtest_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsubmission',
            name='correct_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
