# Generated by Django 5.2.12 on 2026-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_readingtest_passage_1_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='section_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/images/'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='section_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/images/'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='section_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/images/'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='section_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/images/'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading/images/'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading/images/'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading/images/'),
        ),
    ]
