# Generated by Django 5.2.12 on 2026-04-26 19:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_listeningtest_section_1_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='section_1_image',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='section_2_image',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='section_3_image',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='section_4_image',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='passage_1_image',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='passage_2_image',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='passage_3_image',
        ),
        migrations.CreateModel(
            name='ListeningTestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(choices=[(1, 'Section 1'), (2, 'Section 2'), (3, 'Section 3'), (4, 'Section 4')])),
                ('image', models.ImageField(upload_to='listening/images/', validators=[core.models.validate_image_extension])),
                ('label', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.listeningtest')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.IntegerField(choices=[(1, 'Passage 1'), (2, 'Passage 2'), (3, 'Passage 3')])),
                ('image', models.ImageField(upload_to='reading/images/')),
                ('label', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.readingtest')),
            ],
        ),
    ]
