# Generated by Django 5.2.12 on 2026-04-26 19:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_listeningtest_section_1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingtestimage',
            name='image',
            field=models.ImageField(upload_to='reading/images/', validators=[core.models.validate_image_extension]),
        ),
    ]
