# Generated by Django 5.2.12 on 2026-04-29 10:22

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_readingtestimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='audio_file',
            field=models.FileField(upload_to='static/listening/audios/'),
        ),
        migrations.AlterField(
            model_name='listeningtestimage',
            name='image',
            field=models.ImageField(upload_to='static/listening/images/', validators=[core.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='readingtestimage',
            name='image',
            field=models.ImageField(upload_to='static/reading/images/', validators=[core.models.validate_image_extension]),
        ),
        migrations.CreateModel(
            name='WritingTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=250)),
                ('question_type', models.CharField(choices=[('line_graph', 'Line Graph'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('table', 'Table'), ('process', 'Process Diagram'), ('map', 'Map'), ('mixed', 'Mixed Charts')])),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask1Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/writing/images/', validators=[core.models.validate_image_extension])),
                ('label', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.writingtask1')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=250)),
                ('question_type', models.CharField(choices=[('opinion', 'Opinion Essay'), ('discussion', 'Discussion Essay'), ('advantages_disadvantages', 'Advantages and Disadvantages Essay'), ('problem_solution', 'Problem and Solution Essay'), ('direct_question', 'Direct Question Essay'), ('double_question', 'Double Question Essay')])),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
