# Generated by Django 5.2.12 on 2026-05-02 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_examsession_resultstable_exam_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingresults',
            name='task1_word_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writingresults',
            name='task2_word_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
