# Generated by Django 5.2.12 on 2026-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_writingresults_task1_word_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingresults',
            name='task1_word_count',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='writingresults',
            name='task2_word_count',
            field=models.CharField(default='0'),
        ),
    ]
